feat: mock compile
axiom-crypto/axiom-sdk-client pull request #28
Opened 2024-01-16 17:23 UTC by rpalakkal

2024-01-16 22:00 UTC, yi-sun requested changes
Small changes and just confirming one thing on the usage of `mock` previously

2024-01-16 22:00 UTC, yi-sun commented on circuit/js/src/scaffold.ts
> +    const emptyVk = new Array(vkLen).fill(zeroHash);
Let's also do some form of `deadbeef`?

2024-01-16 22:17 UTC, rpalakkal commented on circuit/js/src/cliHandler/compile.ts
> -        mock: true,
not too sure, but doesn't seem like it was being used in `circuit.compile`. cc @ytham

2024-01-18 05:37 UTC, ytham commented on circuit/js/src/cliHandler/compile.ts
> -        mock: true,
it looks like it's only used to pass into AxiomSdkCore, which isn't used for circuit.compile

2024-01-18 05:39 UTC, yi-sun approved these changes

2024-01-18 05:55 UTC, merged