feat: default inputs for circuit compilation
axiom-crypto/axiom-sdk-client pull request #59
Opened 2024-02-09 17:03 UTC by rpalakkal

2024-02-09 17:20 UTC, ytham requested changes
the current [quickstart circuit](https://github.com/axiom-crypto/axiom-quickstart/blob/main/app/axiom/average.circuit.ts) doesn't specify the default inputs in the .circuit.ts file itself, unfortunately. so this might mean a relatively medium/large change in terms of what we've been messaging to users to be the correct flow in terms of our docs and example repos

2024-02-09 18:06 UTC, rpalakkal commented
I was thinking we could merge this at the same time as all the axiom-std changes, which will require documentation/examples to change anyway

2024-02-10 00:09 UTC, ytham commented
> I was thinking we could merge this at the same time as all the axiom-std changes, which will require documentation/examples to change anyway

got it; was there a particular reason why we want to move back to having the inputs in the file itself? 

also, so just so we're completely clear: 
- we would now require the user to have `export const defaultInputs = {...}` in their circuit file 
- remove the input.json file

any thoughts @yi-sun ?

2024-02-12 15:30 UTC, ytham approved these changes
LGTM w/ 1 small fix

2024-02-12 15:30 UTC, ytham commented on circuit/js/src/cliHandler/prove.ts
>      options: {
need to remove `inputs?` here as well

2024-02-12 17:29 UTC, merged